openapi: 3.0.2
info:
  title: NIEM Model API
  description: |

    This project defines a mock static REST API to provide easy access to release and IEPD metadata and components.  This is to support the development of the future NIEM tool strategy and tool prototyping in a simple manner.

    Content will be provided in a separate GitHub project as JSON files using GitHub Pages.  This setup will look and behave similar to a regular REST API, with a few exceptions...

    - Endpoints will end with `.json`, corresponding to the hosted JSON files.
    - No server-side processing is available, so only full data files can be returned (no filtered or paginated results, no query strings on URLs).

    Note that this API is under development and is subject to drastic changes.
  version: '0.1'
  contact:
    url: 'https://github.com/cdmgtri/niem-model-api-specification/'
servers:
  - url: 'https://cdmgtri.github.io/niem-model-api'
tags:
  - name: repository
  - name: models
  - name: versions
  - name: namespaces
  - name: properties
  - name: types
  - name: codes
paths:
  /models.json:
    get:
      summary: Find models
      operationId: getModels
      tags:
        - models
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/modelResponseType'
              example:
                value:
                  - data:
                      name: NIEM
                      source: NIEM Management Office
                      definition: National Information Exchange Model releases
                      description: 'NIEM is a common vocabulary that enables efficient information exchange across diverse public and private organizations. NIEM can save time and money by providing consistent, reusable data terms and definitions, and repeatable processes.'
                      website: 'https://niem.gov'
                    links:
                      href: /model/niem
                      versions:
                        count: 8
                        href: /model/niem/versions
                  - data:
                      name: Hill Valley Arrest Report
                      source: Hill Valley Police Department
                      definition: The Hill Valley Arrest Report is part of a pilot project to extend the standard XYZ Arrest Report message with additional information.
                      description: The Hill Valley Police Department Arrest Report is part of a pilot project to extend the standard XYZ Arrest Report message with additional information.  This includes ...  A message is sent from ... when ... if ... to ...
                      website: 'https://example.com/hvpd/specifications/arrest-report/docs'
                      more: {}
                    links:
                      href: /model/hvpd-arrest-rpt
                      versions:
                        count: 2
                        href: /model/hvpd-arrest-rpt/versions
        default:
          $ref: '#/components/responses/NotFound'
  '/models/{modelID}.json':
    get:
      summary: Find model by ID
      operationId: getModelByID
      tags:
        - models
      parameters:
        - $ref: '#/components/parameters/modelID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelResponseType'
              examples:
                NIEM:
                  value:
                    data:
                      name: NIEM
                      source: NIEM Management Office
                      definition: National Information Exchange Model releases
                      description: 'NIEM is a common vocabulary that enables efficient information exchange across diverse public and private organizations. NIEM can save time and money by providing consistent, reusable data terms and definitions, and repeatable processes.'
                      website: 'https://niem.gov'
                    links:
                      href: /model/niem
                      versions:
                        count: 8
                        href: /model/niem/versions
                Sample IEPD:
                  value:
                    data:
                      name: Hill Valley Arrest Report
                      source: Hill Valley Police Department
                      definition: The Hill Valley Arrest Report is part of a pilot project to extend the standard XYZ Arrest Report message with additional information.
                      description: The Hill Valley Police Department Arrest Report is part of a pilot project to extend the standard XYZ Arrest Report message with additional information.  This includes ...  A message is sent from ... when ... if ... to ...
                      website: 'https://example.com/hvpd/specifications/arrest-report/docs'
                      more: {}
                    links:
                      href: /model/hvpd-arrest-rpt
                      versions:
                        count: 2
                        href: /model/hvpd-arrest-rpt/versions
        '404':
          $ref: '#/components/responses/NotFound'
  '/models/{modelID}/versions.json':
    get:
      summary: Find versions
      operationId: getVersions
      tags:
        - versions
      parameters:
        - $ref: '#/components/parameters/modelID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/versionResponseType'
              example:
                value:
                  - data:
                      modelName: Hill Valley Arrest Report
                      versionNumber: '1.0'
                      baseNIEM: '2.0'
                      packageURL: 'https://github.com/niem/niem-model-api/tree/master/repo/hvpd-arrest-rpt-1.0'
                      uri: 'https://example.com/hvpd/specifications/arrest-report/1.0'
                      changeSummary: Initial IEPD
                    links:
                      href: /versions/hvpd-arrest-rpt-1.0
                      zip: 'https://github.com/niem/niem-model-api/blob/master/zips/hvpd-arrest-rpt-1.0.zip'
                      model: /models/hvpd-arrest-rpt
                      namespaces:
                        count: 3
                        href: /versions/hvpd-arrest-rpt-1.0/namespaces
                      properties:
                        count: 25
                        href: /versions/hvpd-arrest-rpt-1.0/properties
                      types:
                        count: 14
                        href: /versions/hvpd-arrest-rpt-1.0/types
                      codes:
                        count: 205
                        href: /versions/hvpd-arrest-rpt-1.0/codes
                  - data:
                      modelName: Hill Valley Arrest Report
                      versionNumber: '2.0'
                      baseNIEM: '2.0'
                      packageURL: 'https://github.com/niem/niem-model-api/tree/master/repo/hvpd-arrest-rpt-2.0'
                      uri: 'https://example.com/hvpd/specifications/arrest-report/2.0'
                      changeSummary: Version 2.0 adds five additional fields to capture information about ...
                    links:
                      href: /versions/hvpd-arrest-rpt-2.0
                      zip: 'https://github.com/niem/niem-model-api/blob/master/zips/hvpd-arrest-rpt-2.0.zip'
                      model: /models/hvpd-arrest-rpt
                      namespaces:
                        count: 3
                        href: /versions/hvpd-arrest-rpt-2.0/namespaces
                      properties:
                        count: 30
                        href: /versions/hvpd-arrest-rpt-2.0/properties
                      types:
                        count: 18
                        href: /versions/hvpd-arrest-rpt-2.0/types
                      codes:
                        count: 320
                        href: /versions/hvpd-arrest-rpt-2.0/codes
        default:
          $ref: '#/components/responses/NotFound'
  '/versions/{versionID}.json':
    get:
      summary: Find version by ID
      operationId: getVersionByID
      tags:
        - versions
      parameters:
        - $ref: '#/components/parameters/versionID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/versionResponseType'
              examples:
                NIEM:
                  value:
                    data:
                      modelName: NIEM
                      versionNumber: '4.1'
                      baseNIEM: '4.1'
                      packageURL: 'https://github.com/NIEM/NIEM-Releases/tree/niem-4.1'
                      changeSummary: 'See https://github.com/NIEM/NIEM-Releases/blob/niem-4.1/README.md for release notes.'
                    links:
                      href: /versions/niem-4.1
                      zip: 'https://github.com/niem/niem-model-api/blob/master/zips/niem-4.1.zip'
                      model: /models/niem
                      namespaces:
                        count: 58
                        href: /versions/niem-4.1/namespaces
                      properties:
                        count: 11351
                        href: /versions/niem-4.1/properties
                      types:
                        count: 3942
                        href: /versions/niem-4.1/types
                      codes:
                        count: 75114
                        href: /versions/niem-4.1/codes
                Sample IEPD:
                  value:
                    data:
                      modelName: Hill Valley Arrest Report
                      versionNumber: '2.0'
                      baseNIEM: '2.0'
                      packageURL: 'https://github.com/niem/niem-model-api/tree/master/repo/hvpd-arrest-rpt-2.0'
                      uri: 'https://example.com/hvpd/specifications/arrest-report/2.0'
                      changeSummary: Version 2.0 adds five additional fields to capture information about ...
                    links:
                      href: /versions/hvpd-arrest-rpt-2.0
                      zip: 'https://github.com/niem/niem-model-api/blob/master/zips/hvpd-arrest-rpt-2.0.zip'
                      model: /models/hvpd-arrest-rpt
                      namespaces:
                        count: 3
                        href: /versions/hvpd-arrest-rpt-2.0/namespaces
                      properties:
                        count: 30
                        href: /versions/hvpd-arrest-rpt-2.0/properties
                      types:
                        count: 18
                        href: /versions/hvpd-arrest-rpt-2.0/types
                      codes:
                        count: 320
                        href: /versions/hvpd-arrest-rpt-2.0/codes
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    modelResponseType:
      type: object
      properties:
        $schema:
          type: string
        data:
          type: object
          description: 'A data type representing the NIEM data model, an IEPD, an EIEM, or another kind of NIEM-based data model.'
          properties:
            name:
              type: string
              description: A name of a resource.
            definition:
              type: string
              description: A definition for or description of a resource.
            description:
              type: string
              description: A detailed description of a model.
            source:
              type: string
              description: An authoritative source for the model.
            website:
              type: string
              description: A URL for an informational website about this model.
            more:
              type: object
              description: Any additional metadata to be captured.
        links:
          type: object
          description: A data type for metadata about model-related resources.
          properties:
            href:
              type: string
              format: uri-reference
            versions:
              type: object
              description: A data type for metadata about other resources related to the source resource.
              properties:
                count:
                  type: integer
                href:
                  $ref: '#/components/schemas/modelResponseType/properties/links/properties/href'
      example:
        data:
          name: NIEM
          source: NIEM Management Office
          definition: National Information Exchange Model releases
          description: 'NIEM is a common vocabulary that enables efficient information exchange across diverse public and private organizations. NIEM can save time and money by providing consistent, reusable data terms and definitions, and repeatable processes.'
          website: 'https://niem.gov'
        links:
          href: /model/niem
          versions:
            count: 8
            href: /model/niem/versions
    versionResponseType:
      type: object
      properties:
        $schema:
          type: string
        data:
          type: object
          description: A data type for a specific version or release of a model.
          properties:
            modelName:
              type: string
              description: A name of the model to which this version belongs.
            versionNumber:
              type: string
              description: A version number.
            draft:
              type: string
              description: 'A sub-version number, such as a pre-release identifier.'
              example: alpha1
            baseNIEM:
              type: string
              description: A NIEM release that this resource is based on.
              example: '4.0'
            uri:
              type: string
              description: A target namespace or other ID for this model version.
            changeSummary:
              type: string
              description: 'A summary of the changes from the previous version, if applicable.'
            packageURL:
              type: string
              description: A URL for the model package folder.
            more:
              type: object
              description: Any additional metadata to be captured.
        links:
          type: object
          description: A data type for metadata about version-related resources.
          properties:
            href:
              type: string
              format: uri-reference
            zip:
              $ref: '#/components/schemas/versionResponseType/properties/links/properties/href'
            model:
              $ref: '#/components/schemas/versionResponseType/properties/links/properties/href'
            namespaces:
              type: object
              description: A data type for metadata about other resources related to the source resource.
              properties:
                count:
                  type: integer
                href:
                  $ref: '#/components/schemas/versionResponseType/properties/links/properties/href'
            properties:
              $ref: '#/components/schemas/versionResponseType/properties/links/properties/namespaces'
            types:
              $ref: '#/components/schemas/versionResponseType/properties/links/properties/namespaces'
            codes:
              $ref: '#/components/schemas/versionResponseType/properties/links/properties/namespaces'
      example:
        data:
          modelName: Hill Valley Arrest Report
          versionNumber: '2.0'
          baseNIEM: '2.0'
          packageURL: 'https://github.com/niem/niem-model-api/tree/master/repo/hvpd-arrest-rpt-2.0'
          uri: 'https://example.com/hvpd/specifications/arrest-report/2.0'
          changeSummary: Version 2.0 adds five additional fields to capture information about ...
        links:
          href: /versions/hvpd-arrest-rpt-2.0
          zip: 'https://github.com/niem/niem-model-api/blob/master/zips/hvpd-arrest-rpt-2.0.zip'
          model: /models/hvpd-arrest-rpt
          namespaces:
            count: 3
            href: /versions/hvpd-arrest-rpt-2.0/namespaces
          properties:
            count: 30
            href: /versions/hvpd-arrest-rpt-2.0/properties
          types:
            count: 18
            href: /versions/hvpd-arrest-rpt-2.0/types
          codes:
            count: 320
            href: /versions/hvpd-arrest-rpt-2.0/codes
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  parameters:
    modelID:
      name: modelID
      in: path
      required: true
      description: The id of the model to find.
      schema:
        type: string
      example: hvpd-arrest-rpt
    versionID:
      name: versionID
      in: path
      required: true
      description: The id of the version to find.
      schema:
        type: string
      example: hvpd-arrest-rpt-1.0
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 404
            message: The resource was not found
